export const posts = [
  {
    name: "Vincent van Gogh",
    username: "vincey1853",
    location: "Zundert, Netherlands",
    avatar: "avatar-vangogh.jpg",
    post: "post-vangogh.jpg",
    comment: "just took a few mushrooms lol",
    likes: 21,
    likeStatus: false,
    id: 101,
  },
  {
    name: "Gustave Courbet",
    username: "gus1819",
    location: "Ornans, France",
    avatar: "avatar-courbet.jpg",
    post: "post-courbet.jpg",
    comment: "i'm feelin a bit stressed tbh",
    likes: 4,
    likeStatus: false,
    id: 102,
  },
  {
    name: "Joseph Ducreux",
    username: "jd1735",
    location: "Paris, France",
    avatar: "avatar-ducreux.jpg",
    post: "post-ducreux.jpg",
    comment: "gm friends! which coin are YOU stacking up today?? post below and WAGMI!",
    likes: 152,
    likeStatus: false,
    id: 103,
  },
];
